# Generated by Django 3.2.20 on 2023-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
    ]
