# Generated by Django 3.2.20 on 2023-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('mail', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=11)),
                ('sex', models.CharField(max_length=5)),
                ('image', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
