# Generated by Django 3.2.20 on 2023-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_id', models.IntegerField()),
            ],
            options={
                'db_table': 'like',
                'managed': False,
            },
        ),
    ]
