# Generated by Django 3.2.20 on 2023-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.CharField(max_length=45)),
                ('receiver_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'friend_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FriendRequest1',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.CharField(max_length=45)),
                ('sender_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'friend_request1',
                'managed': False,
            },
        ),
    ]
