# Generated by Django 3.2.20 on 2023-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('like', models.CharField(blank=True, max_length=30, null=True)),
                ('blur', models.CharField(blank=True, max_length=200, null=True)),
                ('show', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'photo_upload',
                'managed': False,
            },
        ),
    ]
